var config = {
    'Lang' : 'EN',
    'URL' : '/over/dose/app',
    storeData :{
        'filteringData' : 500,
        'searchingData' : 1500,
        'slideTime': 3000,
        'loginDataKey':'loginData',
        'editDataKey':'editData',
        'deleteDataKey':'deleteData'
    },
    json :{
        dashboardCarouselData : '/services/carousel.json',
        loginUserData:'http://localhost:8333/api/get/registration.json?key=email&value=',
        regData : '/services/registration.json',
        dashboardData :'/services/dashboard.json',
        dashboardDummyData :'/services/dashboardDummy.json',
        putRegData : '/api/add/registration.json',
        putUpcomingDevice : '/api/add/upcomingDevice.json',
        addNewDevice : '/api/add/deviceList.json' ,
        getDeviceList : '/services/deviceList.json' ,
        getRegData:"http://localhost:8333/api/get/registration.json?key=email&value=",
        commonData :'/services/commonData.json',
        commonDataGet:'http://localhost:8333/api/get/commonData.json',
        deviceHistoryInformation :'/services/DeviceHistoryInformation.json',
        deviceHistoryDetails:'http://localhost:8333/api/get/deviceHistoryDetails.json?key=assetNo&value=',
        addLostDeviceData : '/api/add/lostDevice.json',
        dummyLostDeviceData : '/services/dummyLostDevice.json',
        updateRegistrationData : '/api/update/registration.json',
        getLostDeviceData : 'http://localhost:8333/api/get/dummyLostDevice.json?key=assetNumber&value='
    },
    url :{
        adminDashboard:'/views/adminDashboard/adminDashboard.shtml',
        ajaxCallFail : '/views/global/404/404.html',
        myProfile: '/views/myProfile/myProfile.shtml',
        loginPage : '/views/login/login.html',
        signUpPage : 'views/signUp/signUp.html',
        upcomingDevicePage : '/views/upcomingDevice/upcomingDevice.shtml',
        lostDevicePage : '/views/lostDevice/lostDevice.shtml',
        addDevicePage : '/views/addDevice/addDevice.shtml'
    },
    errorMsg : {
        unsuccessfulLogin:'Invalid Credentials',
        successFail : 'Oops something went wrong',
        updateFailed :"The update failed",
        updateAllFail :"The passed data length should be only one for update/replace all operation",
        noRecordFound :"No record found, please pass valid data",
        fileParseError :"Error in parsing file",
        invalidData :"Please provide valid data",
        invalidFileOrData :"Please provide valid file and valid data",
        fileNotFound :"File not found",
        dataAlreadyExists :"The data you are trying to append already exists",
        noUniqueKey :"Please provide unique key",
        alreadyExist :"Record(s) already exist",
        sorry :  "Oops Sorry !!!",
        pleaseSignUp:"please signUp first your email is not registered",
        unsuccessfulRegistration : "Registration failed, Please try again with different email id...",
        unsuccessfulUpdate : "Please enter Data",
        usernameRequired : "Please enter your username",
        userPasswordRequired : "Please enter your password",
        fullNameRequired : "Please enter your  fullName",
        oracleIdRequired : "Please enter your oracleId",
        fieldMaxLength : "Maximum length is 6",
        fieldRequired : "This field is required",
        jobLocationRangeLength : "Address is too short",
        passwordRequired : "Please provide a password",
        passwordRangeLength : "Please enter a value between 6 and 15 characters long",
        newPassword:"enter a new password",
        confirmPasswordRequired : "Please confirm your password",
        confirmPasswordEqualTo : "Please enter the same password as above",
        serialNumberRequired : "Please provide device serial number",
        serialNumberMaxlength : "maximum length is 8",
        assetNumberRequired : "Please provide device asset number",
        deviceTypeRequired : "Please provide device type",
        deviceNameRequired : "Please provide device name",
        osRequired : "Please provide OS Name",
        defaultApplicationsRequired : "Please provide default applications Name",
        sapientEmailRequired : "Only sapient.com email address is allowed.",
        phoneNoRequired : "Please specify a valid phone number",
        deviceNameLettersOnly : "Only letters and spaces are allowed",
        dropBoxMsg : "You must select a value",
        storageNotSupported : "Sorry! No Web Storage support",
        unsuccessfulLostUpdate : "Database update has been failed"
    },
    infoMsg :{
        fieldRequired : "required",
        congrats : "Congrats !!!",
        dropBoxSelect : "Select",
        successfulUpdate : "Record(s) updated successfully",
        successfulDelete : "Record(s) deleted successfully",
        successfulRegistration : "You have registered successfully",
        successfulProfileUpdate: "your changes have been updated",
        successfulLostUpdate : "Database has been updated successfully",
        successfulAdd : "Device added succesfully"
    },
    dashboard :{
        noOfDevice: " Devices",
        allocatedDevice: " Allocated",
        availableDevice: " Available",
        lostDevice:  " Lost"
    }
};

